---- ## SERIE A TEAMS STANDINGS BETWEEN 2018 - 2023 ## ----
USE SCHEMA EXTERNAL_STAGES;
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.TEAMS_STANDINGS_STAGE_S3
    URL = 's3://football-data-bucket-s3/teams_standings/'
    STORAGE_INTEGRATION = AWS_S3_INTEGRATION;

LIST @MANAGE_DB.EXTERNAL_STAGES.TEAMS_STANDINGS_STAGE_S3;

DESC STAGE TEAMS_STANDINGS_STAGE_S3;

SHOW STAGES; 