CREATE SCHEMA IF NOT EXISTS EXTERNAL_STAGES; 
USE SCHEMA EXTERNAL_STAGES;

---- ## BRAZIL TEAMS ## ----

CREATE OR replace STAGE EXTERNAL_STAGES.TEAMS_BRAZIL_STAGE_S3
    URL = 's3://football-data-bucket-s3/teams_brazil/'
     --FILE_FORMAT = ( CSV | JSON | AVRO | ORC | PARQUET | XML )
    -- CREDENTIALS = ( AWS_KEY_ID = ''AWS_SECRET_KEY = '')
    -- ENCRYPTION = ( TYPE = 'AWS_CSE', MASTER_KEY = '')
    -- COPY OPTIONS = ()
    -- TAG = ''
    STORAGE_INTEGRATION = AWS_S3_INTEGRATION; 

LIST @MANAGE_DB.EXTERNAL_STAGES.TEAMS_BRAZIL_STAGE_S3;

DESC STAGE TEAMS_BRAZIL_STAGE_S3;