CREATE OR REPLACE DATABASE MANAGE_DB;

CREATE SCHEMA IF NOT EXISTS MANAGE_DB.STORAGE_INTERAGRATION;

CREATE STORAGE INTEGRATION AWS_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '' -- ARN
    STORAGE_ALLOWED_LOCATIONS = ('') -- URI
    COMMENT = 'Integration to AWS S3';

SHOW INTEGRATIONS; 
DESC INTEGRATION AWS_S3_INTEGRATION;