CREATE TABLE de_para_referee_names (
  referee_name_de VARCHAR(1000),
  referee_name_para VARCHAR(1000)
);

INSERT INTO de_para_referee_names (referee_name_de,referee_name_para) 
VALUES ('Braulio da Silva Machado','Braulio Da Silva Machado'),
('Sávio Pereira','Savio Pereira Sampaio');

drop table de_para_referee_names;

INSERT INTO de_para_referee_names (referee_name_de,referee_name_para) 
VALUES ('Luiz Flavio De Oliveira, Brazil', 'Luiz Flavio De Oliveira'),
('Marcelo De Lima Henrique, Brazil', 'Marcelo De Lima Henrique'),
('Alexandre Vargas Tavares de Jesus, Brazil','Alexandre Vargas Tavares de Jesus'),
('Alisson Sidnei Furtado, Brazil','Alisson Sidnei Furtado'),
('Andre Luiz de Freitas Castro, Brazil','Andre Luiz de Freitas Castro'),
('André Castro','Andre Luiz de Freitas Castro'),
('André Luiz','Andre Luiz de Freitas Castro'),
('Alisson Furtado','Alisson Sidnei Furtado'),
('Anderson Daronco, Brazil','Anderson Daronco'),
('Andre Luiz Skettino Policarpo Bento, Brazil','André Luiz Skettino Policarpo Bento'),
('André Luiz','André Luiz Skettino Policarpo Bento'),
('Arthur Gomes Rabelo, Brazil','Arthur Gomes Rabelo'),
('Braulio Da Silva Machado, Brazil','Braulio Da Silva Machado'),
('Bruno Arleu de Araujo, Brazil','Bruno Arleu de Araujo'),
('Bruno Mota Correia, Brazil','Bruno Mota Correia'),
('Caio Max Augusto Vieira, Brazil','Caio Max Augusto Vieira'),
('Dewson Fernando Freitas da Silva, Brazil','Dewson Fernando Freitas da Silva'),
('Denis da Silva Ribeiro Serafim, Brazil','Denis da Silva Ribeiro Serafim'),
('Diego Pombo Lopez, Brazil','Diego Pombo Lopez'),
('Dyorgines Jose Padovani de Andrade, Brazil','Dyorgines José Padovani de Andrade'),
('Douglas Marques das Flores, Brazil','Douglas Marques das Flores'),
('Edina Alves Batista, Brazil','Edina Alves Batista'),
('Felipe Fernandes de Lima, Brazil','Felipe Fernandes de Lima'),
('Flavio Rodrigues De Souza, Brazil','Flavio Rodrigues De Souza'),
('Gilberto Rodrigues Castro Junior, Brazil','Gilberto Rodrigues Castro Junior'),
('Jean Pierre Goncalves Lima, Brazil','Jean Pierre Goncalves Lima'),
('Heber Lopes','Heber Roberto Lopes'),
('Heber Roberto Lopes, Brazil','Heber Roberto Lopes'),
('Igor Junio Benevenuto, Brazil','Igor Junio Benevenuto'),
('Jean Pierre Goncalves Lima, Brazil','Jean Pierre Goncalves Lima'),
('Jefferson Ferreira de Moraes, Brazil','Jefferson Ferreira de Moraes'),
('Joao Vitor Gobi, Brazil','Joao Vitor Gobi'),
('Jose Mendonca da Silva Junior, Brazil','Jose Mendonca da Silva Junior'),
('José Mendonça','Jose Mendonca da Silva Junior'),
('Leandro Pedro Vuaden, Brazil','Leandro Pedro Vuaden'),
('Leandro Vuaden','Leandro Pedro Vuaden'),
('Maguielson Lima Barbosa, Brazil','Maguielson Lima Barbosa'),
('Luiz Flávio','Luiz Flavio De Oliveira'),
('Marcelo de Lima Henrique','Marcelo De Lima Henrique'),
('Marcelo Aparecido Ribeiro de Souza,Brazil','Marcelo Aparecido Ribeiro de Souza'),
('Marielson Alves Silva,Brazil','Marielson Alves Silva'),
('Matheus Delgado Candancan, Brazil','Matheus Delgado Candancan'),
('Matheus Delgado Candançan','Matheus Delgado Candancan'),
('Paulo Cesar Zanovelli da Silva, Brazil','Paulo Cesar Zanovelli da Silva'),
('Paulo Cesar Zanovelli','Paulo Cesar Zanovelli da Silva'),
('Paulo Roberto Alves Junior,Brazil','Paulo Roberto Alves Júnior'),
('Pablo Ramon Goncalves Pinheiro, Brazil','Pablo Ramon Goncalves Pinheiro'),
('Rafael Rodrigo Klein, Brazil','Rafael Rodrigo Klein'),
('Rafael Traci, Brazil','Rafael Traci'),
('Rafael Trombeta, Brazil','Rafael Trombeta'),
('Ramon Abatti Abel, Brazil','Ramon Abatti Abel'),
('Ramon Abatti','Ramon Abatti Abel'),
('Raphael Claus, Brazil','Raphael Claus'),
('Reway Wagner, Brazil','Wagner Reway'),
('Ricardo Marques Ribeiro, Brazil','Ricardo Marques Ribeiro'),
('Rodrigo Jose Pereira de Lima, Brazil','Rodrigo José Pereira de Lima'),
('Rodrigo Carvalhaes de Miranda, Brazil','Rodrigo Carvalhaes de Miranda'),
('Rodrigo Nunes De Sa, Brazil','Rodrigo Nunes De Sa'),
('Rodolpho Toski Marques, Brazil','Rodolpho Toski Marques'),
('Savio Pereira Sampaio, Brazil','Savio Pereira Sampaio'),
('Sávio Pereira, Brazil','Savio Pereira Sampaio'),  
('Thiago Duarte Peixoto, Brazil','Thiago Duarte Peixoto'),
('Vinicius Goncalves Dias Araujo, Brazil','Vinicius Goncalves Dias Araujo'),
('Vinicius Furlan, Brazil','Vinicius Furlan'),
('Vinicius Gomes do Amara, Brazil','Vinicius Gomes do Amara'),
('Vinicius Gomes','Vinicius Gomes do Amara'),
('Wagner do Nascimento Magalhaes, Brazil','Wagner do Nascimento Magalhaes'),
('Wilton Pereira Sampaio, Brazil','Wilton Pereira Sampaio'),
('Yuri Elino Ferreira Da Cruz, Brazil','Yuri Elino Ferreira Da Cruz'),
('Yuri Elino Ferreira da Cruz','Yuri Elino Ferreira Da Cruz');