CREATE OR REPLACE TASK UPDATE_TEAMS_FIXTURES_STATISTICS_TASK
WAREHOUSE = 'INGESTION_WAREHOUSE'
SCHEDULE = 'USING CRON */1 * * * * UTC'
AS
ALTER PIPE MANAGE_DB.PIPES.TEAMS_FIXTURES_STATISTICS_RAW SET PIPE_EXECUTION_PAUSED = false;


CREATE OR REPLACE TASK UPDATE_TEAMS_FIXTURES_STATISTICS_REFRESH_TASK
WAREHOUSE = 'INGESTION_WAREHOUSE'
SCHEDULE = 'USING CRON */1 * * * * UTC'
AS
ALTER PIPE MANAGE_DB.PIPES.TEAMS_FIXTURES_STATISTICS_RAW REFRESH;

SHOW TASKS;

ALTER TASK UPDATE_TEAMS_FIXTURES_STATISTICS_TASK RESUME;
ALTER TASK UPDATE_TEAMS_FIXTURES_STATISTICS_REFRESH_TASK RESUME;

ALTER TASK UPDATE_TEAMS_FIXTURES_STATISTICS_TASK SUSPEND;
ALTER TASK UPDATE_TEAMS_FIXTURES_STATISTICS_REFRESH_TASK SUSPEND;


