USE DATABASE MANAGE_DB; 

CREATE OR REPLACE SCHEMA MANAGE_DB.PIPES; 

USE SCHEMA PIPES; 

CREATE OR REPLACE PIPE MANAGE_DB.PIPES.TEAMS_STANDINGS_RAW
    AUTO_INGEST = TRUE
    COMMENT = 'Pipe to autoingest standings of brazil teams data between 2018 to 2023 from s3'
 AS 
COPY INTO FOOTBALL_DATA.RAW.TEAMS_STANDINGS
  FROM @MANAGE_DB.EXTERNAL_STAGES.TEAMS_STANDINGS_STAGE_S3
  FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT
  ON_ERROR = SKIP_FILE;

DESC PIPE TEAMS_STANDINGS_RAW;

SELECT * FROM FOOTBALL_DATA.RAW.TEAMS_STANDINGS;

SELECT SYSTEM$PIPE_STATUS('TEAMS_STANDINGS_RAW');

SELECT * FROM TABLE(validate_pipe_load(
PIPE_NAME => 'MANAGE_DB.PIPES.TEAMS_STANDINGS_RAW',
START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
));

SHOW GRANTS ON DATABASE MANAGE_DB;
-- Check schema privileges
SHOW GRANTS ON SCHEMA MANAGE_DB.PIPES;

-- Check table privileges
SHOW GRANTS ON TABLE FOOTBALL_DATA.RAW.TEAMS_STANDINGS;

-- Check stage permissions
SHOW GRANTS ON STAGE MANAGE_DB.EXTERNAL_STAGES.TEAMS_STANDINGS_STAGE_S3;


SELECT *
  FROM TABLE (INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'FOOTBALL_DATA.RAW.TEAMS_STANDINGS',
  START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
  ));  

SELECT * 
  FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATE_RANGE_START=> DATEADD(DAYS,-2,CURRENT_TIMESTAMP()),
  PIPE_NAME => 'MANAGE_DB.PIPES.TEAMS_STANDINGS_RAW'
  ));

ALTER PIPE MANAGE_DB.PIPES.TEAMS_STANDINGS_RAW SET PIPE_EXECUTION_PAUSED = false;

ALTER PIPE MANAGE_DB.PIPES.TEAMS_STANDINGS_RAW REFRESH; 

SELECT * FROM FOOTBALL_DATA.RAW.TEAMS_STANDINGS LIMIT 1000;

SHOW PIPES; 


